create table public.transactions (
  id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete restrict,
  direction text not null check (direction in ('income','expense')), transaction_type text not null default 'adjustment' check (transaction_type in ('sale','expense','income','refund','customer_payment','supplier_payment','transfer','adjustment')),
  lifecycle text not null check (lifecycle in ('proposed','review_required','confirmed','voided')), occurred_at timestamptz not null default public.current_timestamp_utc(), transaction_date date not null, accounting_date date not null,
  counterparty_id uuid references public.parties(id) on delete set null, counterparty_name_snapshot text, description text not null, notes text, category_code text not null,
  currency char(3) not null check (currency ~ '^[A-Z]{3}$'), exchange_rate_to_myr numeric(20,8) check (exchange_rate_to_myr is null or exchange_rate_to_myr > 0),
  subtotal_minor bigint not null default 0 check (subtotal_minor >= 0), discount_minor bigint not null default 0 check (discount_minor >= 0), tax_minor bigint not null default 0 check (tax_minor >= 0), total_minor bigint not null default 0 check (total_minor >= 0),
  payment_status text not null check (payment_status in ('unpaid','partially_paid','paid','not_applicable','unknown')), payment_method_code text, e_invoice_treatment text not null check (e_invoice_treatment in ('individual','consolidated_candidate','self_billed_candidate','not_required','undetermined')),
  source_provenance text not null default 'manual' check (source_provenance in ('manual','receipt','voice','pdf','csv','telegram_text','telegram_voice','whatsapp_demo','bank_statement','external_system')), external_key text, confidence_score numeric(4,3) check (confidence_score between 0 and 1),
  confirmed_at timestamptz, confirmed_by uuid references public.profiles(id) on delete set null, confirmation_notes text, voided_at timestamptz, voided_by uuid references public.profiles(id) on delete set null, void_reason text,
  -- Compatibility snapshots keep the inactive pre-migration adapter readable.
  -- The normalized line items and minor-unit totals above are authoritative.
  source_links jsonb not null default '[]'::jsonb, lines jsonb not null default '[]'::jsonb, totals jsonb not null default '{}'::jsonb, confirmation jsonb, void_metadata jsonb,
  created_at timestamptz not null default public.current_timestamp_utc(), updated_at timestamptz not null default public.current_timestamp_utc(), created_by uuid references public.profiles(id) on delete set null, updated_by uuid references public.profiles(id) on delete set null, version integer not null default 0 check (version >= 0),
  check (total_minor = subtotal_minor - discount_minor + tax_minor), check ((lifecycle <> 'confirmed') or (confirmed_at is not null and confirmed_by is not null)), check ((lifecycle <> 'voided') or (voided_at is not null and voided_by is not null and void_reason is not null)), check ((currency <> 'MYR') or exchange_rate_to_myr is null or exchange_rate_to_myr = 1)
);
create unique index transactions_business_external_key_unique on public.transactions (business_id, external_key) where external_key is not null;
create table public.transaction_line_items (id uuid primary key default gen_random_uuid(), transaction_id uuid not null references public.transactions(id) on delete cascade, product_service_id uuid references public.products_services(id) on delete set null, line_number integer not null check (line_number > 0), description text not null, quantity numeric(20,6) not null check (quantity > 0), unit_code text not null, unit_price_minor bigint not null check (unit_price_minor >= 0), discount_minor bigint not null default 0 check (discount_minor >= 0), charge_minor bigint not null default 0 check (charge_minor >= 0), tax_type_code text not null, tax_rate numeric(7,4) not null check (tax_rate between 0 and 100), tax_minor bigint not null default 0 check (tax_minor >= 0), subtotal_minor bigint not null check (subtotal_minor >= 0), total_minor bigint not null check (total_minor >= 0), classification_code text, country_of_origin char(2), tariff_code text, unique (transaction_id, line_number));
create table public.transaction_status_history (id uuid primary key default gen_random_uuid(), transaction_id uuid not null references public.transactions(id) on delete restrict, from_status text, to_status text not null check (to_status in ('proposed','review_required','confirmed','voided')), reason text, changed_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default public.current_timestamp_utc());
create table public.tags (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, color text, created_at timestamptz not null default public.current_timestamp_utc());
create unique index tags_business_lower_name_unique on public.tags (business_id, lower(name));
create table public.transaction_tags (transaction_id uuid not null references public.transactions(id) on delete cascade, tag_id uuid not null references public.tags(id) on delete cascade, primary key (transaction_id, tag_id));
create table public.evidence_files (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete restrict, source_type text not null check (source_type in ('receipt','voice','pdf','csv','telegram_text','telegram_voice','whatsapp_demo','manual')), storage_bucket text, storage_path text, original_filename text, mime_type text, checksum_sha256 text, size_bytes bigint check (size_bytes >= 0), raw_text text, source_message_reference text, captured_at timestamptz not null default public.current_timestamp_utc(), processing_status text not null default 'received' check (processing_status in ('received','queued','processing','needs_review','processed','failed')), failure_reason text, retention_delete_after timestamptz, deleted_at timestamptz, created_at timestamptz not null default public.current_timestamp_utc(), updated_at timestamptz not null default public.current_timestamp_utc(), created_by uuid references public.profiles(id) on delete set null, check ((storage_bucket is null) = (storage_path is null)), unique (business_id, checksum_sha256));
create table public.extraction_runs (id uuid primary key default gen_random_uuid(), evidence_file_id uuid not null references public.evidence_files(id) on delete restrict, provider text not null, model_name text not null, pipeline_version text not null, raw_provider_result jsonb not null default '{}'::jsonb, structured_output jsonb, warnings jsonb not null default '[]'::jsonb, overall_confidence numeric(4,3) check (overall_confidence between 0 and 1), status text not null check (status in ('pending','running','failed','extracted','needs_review','approved','rejected','superseded')), failure_reason text, started_at timestamptz not null default public.current_timestamp_utc(), completed_at timestamptz, reviewed_by uuid references public.profiles(id) on delete set null, reviewed_at timestamptz, reviewer_notes text, superseded_by_run_id uuid references public.extraction_runs(id) on delete set null, created_at timestamptz not null default public.current_timestamp_utc(), updated_at timestamptz not null default public.current_timestamp_utc());
create table public.extraction_field_results (id uuid primary key default gen_random_uuid(), extraction_run_id uuid not null references public.extraction_runs(id) on delete cascade, field_path text not null, extracted_value jsonb, reviewed_value jsonb, confidence numeric(4,3) check (confidence between 0 and 1), evidence jsonb not null default '[]'::jsonb, status text not null default 'proposed' check (status in ('proposed','accepted','corrected','rejected')), unique (extraction_run_id, field_path));
create table public.transaction_evidence_links (transaction_id uuid not null references public.transactions(id) on delete restrict, evidence_file_id uuid not null references public.evidence_files(id) on delete restrict, extraction_run_id uuid references public.extraction_runs(id) on delete set null, relationship text not null check (relationship in ('primary','supporting','derived')), notes text, primary key (transaction_id, evidence_file_id, relationship));
create trigger transactions_set_updated_at before update on public.transactions for each row execute function public.set_updated_at(); create trigger evidence_files_set_updated_at before update on public.evidence_files for each row execute function public.set_updated_at(); create trigger extraction_runs_set_updated_at before update on public.extraction_runs for each row execute function public.set_updated_at();
create index transactions_business_date_idx on public.transactions (business_id, transaction_date desc); create index transactions_business_lifecycle_idx on public.transactions (business_id, lifecycle) where lifecycle <> 'voided'; create index evidence_files_business_status_idx on public.evidence_files (business_id, processing_status); create index extraction_runs_evidence_status_idx on public.extraction_runs (evidence_file_id, status);
